# External taps

tap "styrainc/packages"

# Shell and terminal
brew "starship"
brew "bottom"
brew "htop"
brew "fzf"
brew "fnm"
brew "ripgrep"

# Core CLI utilities
brew "bat"
brew "coreutils"
brew "fd"
brew "jq"
brew "shellcheck"
brew "shfmt"
brew "watchman"
brew "wget"

# Git and repo workflow
brew "git-delta"
brew "glab"
brew "lefthook"
brew "pre-commit"

# Editors and local dev
brew "neovim"
brew "prettier"
brew "pyenv"
brew "python@3.11"
brew "python@3.12"
brew "ruby-install"
brew "virtualenv"

# Infra and platform tooling
brew "caddy"
brew "hadolint"
brew "nmap"
brew "open-mpi"
brew "styrainc/packages/regal"
brew "tfenv"
brew "tflint"

# Language, package, and runtime support
brew "automake"
brew "bison"
brew "code-server"
brew "composer"
brew "dockutil"
brew "gdbm"
brew "httpie"
brew "libffi"
brew "openssl@1.1"
brew "rtmpdump"
brew "vips"
